import {RULES,ITEMS,EQUIPMENT,MEMENTOS,STATUSES,ENEMIES,WARDENS} from './data.js';
const s={screen:'start',players:[],ev:3,badges:0,enemies:[],log:[],encounterVal:0,lastAttacker:null};
const app=document.getElementById('app');
const r=(n=6)=>Math.floor(Math.random()*n)+1; const log=m=>{s.log.unshift(`[${new Date().toLocaleTimeString()}] ${m}`);render();};
const parse=(range,roll)=>range.includes('-')?(()=>{const[a,b]=range.split('-').map(Number);return roll>=a&&roll<=b;})():Number(range)===roll;
function render(){app.innerHTML=s.screen==='start'?start():s.screen==='run'?run():browser();bind();}
function start(){return `<section class='panel'><h2>Start Run</h2><label>Players <select id='pc'>${[1,2,3,4].map(n=>`<option>${n}</option>`).join('')}</select></label><div id='mem'></div><button id='go'>Start Run</button><button id='browse'>Card Browser</button></section>`;}
function initPlayers(n){s.players=[...Array(n)].map((_,i)=>({id:i+1,hp:20,atk:1,def:1,run:1,memento:MEMENTOS[0].name,mementoTapped:false,activeItem:null,equipment:[],statuses:[],acted:false,usedItem:false,defending:false}));}
function run(){return `<div class='grid'><section class='panel'><h3>Run</h3><p>EV:${s.ev} <button data-a='ev+' >+</button><button data-a='ev-'>-</button> | Badges:${s.badges} <button data-a='b+' >+</button><button data-a='b-'>-</button></p><button data-a='enc'>Generate Encounter</button><button data-a='enemy'>Enemy Phase</button><button data-a='end'>End Round</button><button data-a='win'>Win Encounter</button><button data-a='loot'>Draw Loot</button><button data-a='warden'>Challenge Warden</button><button data-a='refresh'>Refresh Mementos</button><button data-a='reset'>Reset</button></section><section class='panel'><h3>Enemies (${s.enemies.length}/${RULES.maxEnemiesOnField}) VAL:${s.encounterVal}</h3>${s.enemies.map((e,i)=>`<div class='card'><b>${e.name}</b> HP:${e.hp}/${e.maxHp} VAL:${e.val}<button data-k='ehp+' data-i='${i}'>+HP</button><button data-k='ehp-' data-i='${i}'>-HP</button></div>`).join('')}</section><section class='panel'><h3>Players</h3>${s.players.map((p,i)=>`<div class='card'><b>P${p.id}</b> HP:${p.hp}<button data-k='php+' data-i='${i}'>+HP</button><button data-k='php-' data-i='${i}'>-HP</button><br>ATK:${p.atk} DEF:${p.def} RUN:${p.run}<br>Memento:${p.memento} ${p.mementoTapped?'(TAPPED)':''}<button data-k='tap' data-i='${i}'>Tap/Untap</button><br>Item:${p.activeItem?`${p.activeItem.name} (${p.activeItem.remaining})`:'None'}<button data-k='useItem' data-i='${i}'>Use Item</button><button data-k='id+' data-i='${i}'>+Dur</button><button data-k='id-' data-i='${i}'>-Dur</button><br>Equip:${p.equipment.map((e,j)=>`${e.name}(${e.durability})<button data-k='ue' data-i='${i}' data-j='${j}'>Use</button>`).join(' ')||'None'}<button data-k='addEq' data-i='${i}'>+Equip</button><br>Status:${p.statuses.map(st=>`${st.name}(${st.remaining})`).join(',')||'None'}<button data-k='addSt' data-i='${i}'>+Status</button><button data-k='rmSt' data-i='${i}'>-Status</button><br><button data-k='atk' data-i='${i}'>Basic ATK</button><button data-k='def' data-i='${i}'>Defend</button><button data-k='run' data-i='${i}'>RUN</button></div>`).join('')}</section><section class='panel'><h3>Log</h3><pre>${s.log.slice(0,80).join('\n')}</pre><button id='cards'>Cards</button></section></div>`;}
function browser(){const block=(t,a)=>`<section class='panel'><h3>${t}</h3>${a.map(x=>`<div class='card'><b>${x.name}</b><pre>${JSON.stringify(x,null,2)}</pre></div>`).join('')}</section>`; return `<button id='back'>Back</button>${block('Enemies',ENEMIES)}${block('Items',ITEMS)}${block('Equipment',EQUIPMENT)}${block('Statuses',STATUSES)}${block('Mementos',MEMENTOS)}${block('Wardens',WARDENS)}`;}
function bind(){if(s.screen==='start'){const pc=document.getElementById('pc'),mem=document.getElementById('mem');const paint=()=>{mem.innerHTML=[...Array(Number(pc.value))].map((_,i)=>`P${i+1}:<select id='m${i}'>${MEMENTOS.map(m=>`<option>${m.name}</option>`).join('')}</select><br>`).join('');};pc.onchange=paint;paint();document.getElementById('go').onclick=()=>{initPlayers(Number(pc.value));s.players.forEach((p,i)=>p.memento=document.getElementById(`m${i}`).value);s.screen='run';log('Run started.');};document.getElementById('browse').onclick=()=>{s.screen='browser';render();};return;} if(s.screen==='browser'){document.getElementById('back').onclick=()=>{s.screen='start';render();};return;}
app.querySelectorAll('button[data-a]').forEach(b=>b.onclick=()=>actions(b.dataset.a)); app.querySelectorAll('button[data-k]').forEach(b=>b.onclick=()=>playerAction(b.dataset.k,Number(b.dataset.i),Number(b.dataset.j))); document.getElementById('cards').onclick=()=>{s.screen='browser';render();};}
function actions(a){if(a==='enc'){generateEncounter();} if(a==='enemy'){enemyPhase();} if(a==='end'){endRound();} if(a==='win'){s.ev+=RULES.evIncreaseOnWin;s.enemies=[];s.encounterVal=0;log(`Encounter won. EV +${RULES.evIncreaseOnWin}`);} if(a==='loot'){drawLoot(s.encounterVal||s.ev);} if(a==='warden'){challengeWarden();} if(a==='refresh'){s.players.forEach(p=>p.mementoTapped=false);log('Mementos refreshed.');} if(a==='reset'){location.reload();} if(a==='ev+')s.ev++;if(a==='ev-')s.ev=Math.max(1,s.ev-1);if(a==='b+')s.badges++;if(a==='b-')s.badges=Math.max(0,s.badges-1);render();}
function generateEncounter(){s.enemies=[];let budget=s.ev;while(budget>0&&s.enemies.length<RULES.maxEnemiesOnField){const opts=ENEMIES.filter(e=>e.val<=budget&&s.enemies.filter(x=>x.name===e.name).length<e.max);if(!opts.length)break;const e=opts[Math.floor(Math.random()*opts.length)];s.enemies.push({...e,maxHp:e.hp,atkBuff:0,defBuff:0});budget-=e.val;}s.encounterVal=s.enemies.reduce((a,e)=>a+e.val,0);log(`Encounter generated. EV ${s.ev}, field VAL ${s.encounterVal}.`);}
function enemyPhase(){s.enemies.forEach(e=>{const d6=r(6),act=e.actions.find(a=>parse(a.split('|')[0],d6))?.split('|')[1]||'No action';const t=target();log(`${e.name} rolled d6=${d6}, d4 target=${t.roll}->P${t.player.id}: ${act}`);});}
function target(){if(s.players.length===1) return {roll:1,player:s.players[0]}; let roll=r(4); if(s.players.length===3&&roll===4&&RULES.threePlayerTargetRule==='reroll4') roll=r(3); const idx=Math.min(roll,s.players.length)-1; return {roll,player:s.players[idx]};}
function playerAction(k,i,j){const p=s.players[i]; if(!p)return; if(k==='atk'||k==='def'){for(const st of [...p.statuses]){const d=r(6);const res=(STATUSES.find(x=>x.name===st.name)?.table||[]).find(t=>parse(t.split('|')[0],d));log(`P${p.id} status ${st.name} rolled ${d}: ${res?res.split('|')[1]:'No special effect'}`);} }
if(k==='atk'){p.acted=true;s.lastAttacker=p.id;log(`P${p.id} basic ATK for ${p.atk}.`);} if(k==='def'){p.acted=true;p.defending=true;log(`P${p.id} defends for ${p.def}.`);} if(k==='run'){p.acted=true;log(`P${p.id} RUN attempt.`);} if(k==='useItem'){const it=ITEMS[Math.floor(Math.random()*ITEMS.length)]; if(RULES.singleActiveItem&&p.activeItem&&!RULES.replaceActiveItem){log(`P${p.id} cannot use new item yet.`);} else {p.activeItem={name:it.name,remaining:it.duration};p.usedItem=true;log(`P${p.id} uses item ${it.name} (${it.duration}).`);} } if(k==='addEq'){const e=EQUIPMENT[Math.floor(Math.random()*EQUIPMENT.length)];p.equipment.push({name:e.name,durability:e.durability,text:e.text});log(`P${p.id} equipped ${e.name}.`);} if(k==='ue'){const e=p.equipment[j];if(e){e.durability--;log(`P${p.id} used equipment ${e.name}, durability now ${e.durability}.`);if(e.durability<=0)p.equipment.splice(j,1);}} if(k==='addSt'){const st=STATUSES[Math.floor(Math.random()*STATUSES.length)];p.statuses.push({name:st.name,remaining:st.duration});log(`P${p.id} gained status ${st.name}.`);} if(k==='rmSt'){p.statuses.pop();} if(k==='php+')p.hp++;if(k==='php-')p.hp--;if(k==='ehp+')s.enemies[i].hp++;if(k==='ehp-')s.enemies[i].hp--;if(k==='id+'&&p.activeItem)p.activeItem.remaining++;if(k==='id-'&&p.activeItem)p.activeItem.remaining--;if(k==='tap')p.mementoTapped=!p.mementoTapped; render();}
function endRound(){s.players.forEach(p=>{if(p.activeItem){p.activeItem.remaining--;if(p.activeItem.remaining<=0){log(`P${p.id} item expired: ${p.activeItem.name}`);p.activeItem=null;}} p.statuses.forEach(st=>st.remaining--); p.statuses=p.statuses.filter(st=>st.remaining>0); p.acted=false; p.usedItem=false; p.defending=false;});log('Round ended; durations/statuses ticked.');}
function drawLoot(budget){let rem=budget,picks=[],tries=0,pool=[...ITEMS,...EQUIPMENT];while(rem>0&&tries<60){tries++;const c=pool[Math.floor(Math.random()*pool.length)];const v=c.value||1;if(v<=rem){picks.push(c.name);rem-=v;}}log(`Loot draw budget ${budget}: ${picks.join(', ')||'none'} (remaining ${rem}).`);}
function challengeWarden(){const w=WARDENS[0];if(s.ev<w.evReq||s.badges<w.badgeReq){log(`Warden locked: needs EV ${w.evReq} and badges ${w.badgeReq}.`);return;}s.enemies=[{name:w.name,hp:w.hp,maxHp:w.hp,val:w.val,actions:w.actions,keywords:w.keywords}];s.encounterVal=w.val;log(`Challenged Warden ${w.name}. Setup: ${w.setup}`);for(let i=0;i<2;i++){const jm=ENEMIES.find(e=>e.name==='Junk Mail');if(jm)s.enemies.push({...jm,maxHp:jm.hp});}}
render();
